Test_9/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Test_9.Models.DepartmentModels;
using Test_9.Services.Departments;

namespace Test_9.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var model = _departmentService.GetDepartments();
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            DepartmentCreateModel model = _departmentService.GetDeparmentCreateModel();
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(DepartmentCreateModel model)
        {
            if (ModelState.IsValid)
            {
                _departmentService.CreateDepartment(model);
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit(Guid? id)
        {
            if (!id.HasValue)
            {
                ViewBag.BadRequestMessage = "Department id cannot be NULL";
                return View("BadRequest");
            }

            var departmentEditMpdel = _departmentService.GetDepartmentById(id.Value);

            return View(departmentEditMpdel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(DepartmentEditModel model)
        {
            try
            {
                _departmentService.EditDepartment(model);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return StatusCode(500, ex.Message);
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (!id.HasValue)
            {
                ViewBag.BadRequestMessage = "News id cannot be NULL";
                return View("BadRequest");
            }
            bool isDeleted = await _departmentService.DeleteDepartmentAsync(id.Value);
            return RedirectToAction("Index");
        }
    }
}

Test_9/Views/Department/Create.cshtml
@model Test_9.Models.DepartmentModels.DepartmentCreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>DepartmentCreateModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Test_9/Views/Department/Edit.cshtml
@model Test_9.Models.DepartmentModels.DepartmentEditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DepartmentEditModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentName" class="control-label"></label>
                <input asp-for="DepartmentName" class="form-control" />
                <span asp-validation-for="DepartmentName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Test_9/Views/Department/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using Test_9.DAL.Entities
@model IEnumerable<Test_9.Models.DepartmentModels.DepartmentModel>
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


@{
    ViewData["Title"] = "Index";
}

<h1 style="margin-top:50px">Отделы</h1>

<p style="margin-top:15px ">
    <a asp-action="Create" style="color: red">Добавить отдел</a>
</p>
<table class="table" style="margin-top:40px ">
    <thead class="header">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DepartmentName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DepartmentName)
                </td>
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("admin"))
                {
                    <td>
                        <a asp-controller="Department" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Редактировать</a>

                    </td>
                    <td>
                        @{ await Html.RenderPartialAsync("_DeletePartialView", item);}
                    </td>
                }
            </tr>
        }
        </tbody>
    </table>

    <style>
        .header {
            background-color: rgb(8, 49, 115);
            font-family: sans-serif;
            text-transform: uppercase;
            color: white;
            letter-spacing: 2px;
        }
    </style>

Test_9/Views/Department/_DeletePartialView.cshtml
@model Test_9.Models.DepartmentModels.DepartmentModel

<form asp-action="Delete">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <span asp-validation-for="DepartmentName" class="text-danger"></span>
        <div class="form-group">
            <input asp-for="Id" value="@Model.Id" type="hidden" class="form-control " />
            <input type="submit" value="Удалить" class="btn btn-danger" />
        </div>
    </div>
</form>